### ISSUE TITLE
Chromecast support broken?

### ISSUE THREAD

**Issue by nog3** [vincentbernat/dashkiosk#10]
Hiya,

In my console log for dashkiosk I can see it finds the chromecast device but it never displays it in the web interface for dashkiosk.

Here's the relevant log file part - 

info: Express server listening on port 9400 in production mode
info: New Chromecast device discovered 
{ address: '192.168.1.3',
  port: 8009,
  id: '5aa559b51ba55f5478249094ceb489c6',
  friendlyName: 'pikeletcast' }

I've tried both Nodecastor and dashkiosk and both can locate and identify chromecasts but seem to largely be unable to launch any dashboard/content.

I've tried this with two separate devices both running the latest chromecast versions (pikeletcast is rooted with Eureka rom but t hat should not change anything.)

**Comment by Magic01** [comment]
Could it be, that this issue is happening again? 
I run the docker image vincentbernat/dashkiosk:latest today with --net=haost and can see that there are logs New Chromecast device discovered, but they are not appearing on the admin page.

**Comment by vincentbernat** [comment]
You can try `./node_modules/nodecastor/bin/chromecast discover`, then `chromecast status x.x.x.x`. I think you'll get the ID of the home application.

**Comment by Magic01** [comment]
` ./node_modules/nodecastor/bin/chromecast discover
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
info: + XXX-XXX-XXxxxxxxx (192.168.60.73:8009) [d10a27f155a2f0543e378e2320f7ae9a]
info: + XXX-XXX-XXxxxxxxx (192.168.60.90:8009) [27390a98a7bf4a4bb973ed51b480e633]
`
and 
` ./node_modules/nodecastor/bin/chromecast status 192.168.60.73
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
info: Status received:
{ isActiveInput: true,
  isStandBy: false,
  userEq: {},
  volume:
   { controlType: 'master',
     level: 0.019999999552965164,
     muted: false,
     stepInterval: 0.009999999776482582 } }
`
Not really an ID there, or?

**Comment by vincentbernat** [comment]
Hum, there should have been a `applications` thing here. In `chromecast.js`, could you modify `onHomeScreen()` function and add a `logger.info('hello', status)` as a first line?
