### ISSUE TITLE
Dashkiosk hangs when too many devices connect at once

### ISSUE THREAD

**Issue by ned-kelly** [vincentbernat/dashkiosk#104]
So running dashkiosk within docker, with about 500 devices connected to it... (internal company dashboards) When I restart the container and all dashboards try to reconnect, the process will just hang (with no log outputs)...

Any pointers on where to look / begin debugging?

The HTTP port also does not reply, so I believe it's the whole app hanging and not just the websockets piece of the puzzle.

Sorry I don't have much more to go on than this ... It's not a CPU/Memory issue - the host is a 8 core box with 32gb ram and SSD's.

Cheers,

**Comment by vincentbernat** [comment]
Sorry, I don't have much experience at this scale.

**Comment by ned-kelly** [comment]
Ended up adding [socket.io-redis](https://github.com/socketio/socket.io-redis) in the mix and sharding the app behind caddy webserver.
