### ISSUE TITLE
Issue with Nodecastor

### ISSUE THREAD

**Issue by MartinHenriksson** [vincentbernat/dashkiosk#112]
Hello,

I have bee a user of this exellent software for some time, but decided it was time to upgrade the server its running on and thus refresh the install completely.

I am now however, running into a issue when attempting to start the server with Chromecast support enabled:
![image](https://user-images.githubusercontent.com/21305601/185945501-9cb61618-d588-4adc-9e3b-da6c4bde07a2.png)

The error "Chromecast support is disabled due to an error when importing ´nodecastor´" is a bit cryptic for me and I seem unable to identify anyone else that has had this issue after searching.

Ubuntu 22 LTS
Chromecasts are found using avahi-browse

But as I am unable to activate the Chromecast support, no results on the Admin UI to add them to groups for dashboards.

Is there any chance of assistance?

**Comment by vincentbernat** [comment]
Run `node` manually and try `require('nodecastor')` to get the full error.

**Comment by MartinHenriksson** [comment]
Hey Vincent and thank you for taking the time to reply.
I resolved this by running npm install nodecast - for some reason this was needed after the dashkiosk install.

**Comment by vincentbernat** [comment]
Yes, it's needed. Optional dependencies should be installed by default with `npm install`.
