### ISSUE TITLE
Troubleshooting blank display

### ISSUE THREAD

**Issue by graham-m-dunn** [vincentbernat/dashkiosk#16]
Hi,

I have an internal dashboard (written with the same framework as Dashing) that just displays as a white page (both in a browser hitting /receiver and a Chromecast). The original URL loads fine in Chrome, other dashboards (Google Slide, leftronic, geckoboard) load just fine using DashKiosk. I'm not sure where else to look for problems, are there any diagnostics that can be viewed when a screen is loading a URL?

Thanks,
Graham

**Comment by lgo33** [comment]
for anyone else who is coming here, trying to get this to work with dashing without nginx. I just had to add the following line to 'config.ru' to disable passing of the `X-Frame-Option`

set :protection, :except => :frame_options

**Comment by vincentbernat** [comment]
Thanks. I have added that to the documentation in 5719649ac775.
