### ISSUE TITLE
webgl

### ISSUE THREAD

**Issue by ghost** [vincentbernat/dashkiosk#18]
this is a question, not an issue.

i want to project to many chromecasts webgl 3d content.
the chromecast does not support webgl, so the only way to do it is to use the equivalent of tabcasting, where the content is rendered on the "server", and then projected to the ChromeCast as a video feed.

i am wondering if the current code can / wants to support this scenario ?

thank you !!!

**Comment by vincentbernat** [comment]
There is nothing like that in the current code and no plan to do that. You should try with an Android key instead. This is a little bit more expensive, but the helper application supports WebGL. Otherwise, if you find a project able to stream a web page, you can just point Dashkiosk to it.

**Comment by vincentbernat** [comment]
Not much to do about that. For WebGL, use an Android key or some NUC. A Chromecast cannot handle that.
