### ISSUE TITLE
Preload new site in background

### ISSUE THREAD

**Issue by andymac4182** [vincentbernat/dashkiosk#21]
Would it be hard to get the next site to load a configurable time period before hand eg 5 seconds. Behind the existing site then hiding the current site to show the one behind. That will allow sites like Grafana to load completely before being displayed.

**Comment by vincentbernat** [comment]
❦  4 mai 2015 22:39 -0700, Andrew McClenaghan <notifications@github.com> :

> Would it be hard to get the next site to load a configurable time
> period before hand eg 5 seconds. Behind the existing site then hiding
> the current site to show the one behind. That will allow sites like
> Grafana to load completely before being displayed.

That's already implemented. That's the "delay" option. See in the demo:
 http://dashkiosk.app.exo.io/admin#/groups
-- 
A horse!  A horse!  My kingdom for a horse!
		-- Wm. Shakespeare, "Richard III"

**Comment by andymac4182** [comment]
I just saw that option when going through the code to see how hard it would be to implement. Works exactly as I was hoping. 

Thanks :)

**Comment by vincentbernat** [comment]
Service.
