### ISSUE TITLE
Grunt build failing

### ISSUE THREAD

**Issue by chad-upton** [vincentbernat/dashkiosk#22]
Not sure where to go with this one, as it's not building the dist directory.

```
Running "imagemin:dist" (imagemin) task
✔ build/images/dark-wood.jpg (saved 1.45 kB)
Warning: ** Error:  Use --force to continue.

Aborted due to warnings.
```

When running grunt imagemin --force
```
Running "imagemin:dist" (imagemin) task
✔ build/images/dark-wood.jpg (saved 1.45 kB)
Warning: ** Error:  Used --force, continuing.
Fatal error: Cannot read property 'diffSizeRaw' of undefined
```

**Comment by vincentbernat** [comment]
Instead of `--force`, try with `--debug`. I suspect that you need to install `jpegtran`. This plugin ships with some prebuilt binary but that doesn't work everywhere. In this case, you need to provide your own. You are on Linux, right?

**Comment by chad-upton** [comment]
Correct that fixed it.  Thanks!

**Comment by falzm** [comment]
I do have a similar issue trying to build Dashkiosk:

```
# grunt --debug
...
Running "imagemin:dist" (imagemin) task
[D] Task source: /root/dashkiosk-2.5.0/node_modules/grunt-contrib-imagemin/tasks/imagemin.js
Warning: Bad argument Use --force to continue.

Aborted due to warnings.
```

Environment:
- Ubuntu Linux 14.10 Utopic
- NodeJS v0.10.25
- NPM 1.4.21
- jpegtran installed (libjpeg-turbo version 1.3.0 (build 20131219))
Let me know if I can provide more information.

**Comment by vincentbernat** [comment]
Do you have optipng as well? If installing it doesn't solve the issue, also, try:

```
rm -rf node_modules/grunt-contrib-imagemin
npm cache clean
npm install grunt-contrib-imagemin
```

**Comment by falzm** [comment]
Installing optipng didn't solve the issue, but the rest of your instructions did. Thanks!

**Comment by vincentbernat** [comment]
Reproductible builds! ;-)

**Comment by falzm** [comment]
Speaking of which... Could it be possible to provide a Dockerfile in the sources, to facilitate the installation/isolate all the dependencies in a container? :)

**Comment by vincentbernat** [comment]
Do you mean that: https://github.com/vincentbernat/dashkiosk/blob/master/Dockerfile ;-)

**Comment by falzm** [comment]
Rho, I'm sorry... The idea popped in my head, didn't even bother looking first... Great! :D
