### ISSUE TITLE
Feature: List of Dashboards with edit, duplicate, remove.

### ISSUE THREAD

**Issue by chad-upton** [vincentbernat/dashkiosk#24]
Would be a nice feature if we could just add a list of dashboards in the admin, and copy them to whichever group we want.

We have instances were some dashboards are displayed in multiple groups, and instead of having to go to each one and type it all in.  It would be great just to duplicate it.

Basically a left pane with dashboard management.

Loving this project so far!  Thanks for all your work on it.

**Comment by vincentbernat** [comment]
Hey @chad-upton, I have been proposed to enable drag-and-drop of dashboards from one group to another (idea from @falzm). This is simple enough to do and not invasive on the interface. Would it match what you want?

**Comment by vincentbernat** [comment]
Drag'n'drop would copy, not move.
