### ISSUE TITLE
Chromecast Not Able to Reconnect

### ISSUE THREAD

**Issue by zonajustin06** [vincentbernat/dashkiosk#25]
So Dashkiosk & Nodecastor work perfectly when I already have my chromecast running and start up the Dashkiosk server from the command line.  The Chromecast is found and switches over to the dashboard and works great.

The problem that I'm experiencing occurs when the chromecast / tv is turned off and then turned back on.  This is the output I get:

info: Chromecast device detected on home screen 
{ id: '2bf63f93131d2b50b0a09d314897e4e6',
  name: undefined,
  chromecast: 'Chromecast7089' }
error: Unable to run Dashkiosk application 
{ stack: 
   [ 'Error: no answer from Chromecast device',
     '    at null._onTimeout (/dashkiosk-2.5.0/dist/node_modules/nodecastor/lib/channel.js:235:12)',
     '    at Timer.listOnTimeout (timers.js:110:15)' ],
  message: 'no answer from Chromecast device' }

I can let it sit for hours, and nothing changes.  The chromecast just sits on the home screen.  The same happens if I turned the tv on and off.  If i restart the Dashkiosk server, it immediately finds the Chromecast and the dashboard is instantly displayed.  Any ideas what could be causing this problem with the reconnect?

**Comment by vincentbernat** [comment]
When you say you sit for hours, do you get the same error every 2 minutes? With this error, Dashkiosk should retry to contact the Chromecast device every 2 minutes.

**Comment by zonajustin06** [comment]
I only get the error described above after I turn the chromecast / tv back on.  If I let it sit, I get "info: Rescan Chromecast devices" every few minutes - but not the full communication error.  And it doesn't say that chrome casts were found or not.

**Comment by plitewaikato** [comment]
I have a similar problem, I found that killing the node process on the
Dashkiosk server every half hour allows Chromecast discovery to resume
normally.

**Comment by vincentbernat** [comment]
When the problem happens, could you try to run the Dashkiosk app through nodecastor instead:

```
./node_modules/nodecastor/bin/chromecast discover
./node_modules/nodecastor/bin/chromecast --debug dashkiosk discovered.ip http://www.google.com
```

And tell what happens at the end.

**Comment by vincentbernat** [comment]
I have some difficulties to debug the problem since my Chromecast is unwilling to switch to debug mode. I find indications that a firmware update could solve the problem but I have the most recent one. Just in case, could you check that "Guest mode" is disabled? Which firmware are you running on the Chromecast?

**Comment by zonajustin06** [comment]
As an update, I was about to try the debug mode this morning, but my chromecast automatically updated itself when I turned it on.  Now the problem seems to be gone.  When I turn the tv off and back on, it connects with Dashkiosk instantly and displays the dashboard.  I'll keep messing with it, but for whatever reason it seems that the most recent update fixed the issue...

**Comment by vincentbernat** [comment]
Oh, well, that's convenient! ;-)

Which firmware version did it update to?

**Comment by zonajustin06** [comment]
Very convenient.  It was updated to firmware 32904.

**Comment by vincentbernat** [comment]
It is more recent than mine (27946). I hope I will get updated soon and this will fix the ability to debug too.

@plitewaikato could you also check your firmware and maybe force a reboot to get the new one and report whatever it works better for you now?

In any case, as soon as you detect a regression in the Chromecast support, open an issue. I am only testing the support just before a release since I don't use them anymore at work.

**Comment by plitewaikato** [comment]
My signage Chromecasts are all running 32904.  It's definitely a Chromecast
discovery issue, as rebooting the node process on the server enables an
almost instant reconnect on the Chromecast receivers and the standard HTML
receiver based screens don't lose connection.

**Comment by vincentbernat** [comment]
We can likely fix that. Do you get the same error message (`Unable to run Dashkiosk application`) or is it something a bit different?

**Comment by plitewaikato** [comment]
Yeah, that same message:

[31merror[39m: Unable to run Dashkiosk application
{ stack:
   [ [32m'Error: expected a RECEIVER_STATUS message'[39m,
     [32m'    at
/Volumes/SkyDrive/Web/Statusboard/dashkiosk/dist/node_modules/nodecastor/lib/application.js:37:12'[39m,
     [32m'    at CastChannel.answer
(/Volumes/SkyDrive/Web/Statusboard/dashkiosk/dist/node_modules/nodecastor/lib/channel.js:219:9)'[39m,
     [32m'    at CastChannel.emit (events.js:117:20)'[39m,
     [32m'    at CleartextStream.readable
(/Volumes/SkyDrive/Web/Statusboard/dashkiosk/dist/node_modules/nodecastor/lib/channel.js:124:10)'[39m,
     [32m'    at CleartextStream.emit (events.js:92:17)'[39m,
     [32m'    at emitReadable_ (_stream_readable.js:427:10)'[39m,
     [32m'    at _stream_readable.js:420:7'[39m,
     [32m'    at process._tickDomainCallback (node.js:486:13)'[39m ],
  message: [32m'expected a RECEIVER_STATUS message'[39m }

**Comment by vincentbernat** [comment]
The problem may be a bit different but unfortunately, the error message isn't helpful. Could you edit `node_modules/nodecastor/lib/application.js` and edit line 37 with this:

```js
        cb(new Error('expected a RECEIVER_STATUS message, got ' + message.data.type + ' instead'));
```

This should give message that was received instead of `RECEIVER_STATUS`.

**Comment by plitewaikato** [comment]
Change made, just waiting for the error to appear.  Thanks for all your
help Vincent, it's a great product!

**Comment by plitewaikato** [comment]
Got a new error instead.  :)  Apologies for the wall of text.

[34mdebug[39m: Got an error: connect Unknown system errno 64
[31merror[39m: An error occurred with some Chromecast device { stack:
   [ 'Error: connect Unknown system errno 64',
     '    at errnoException (net.js:905:11)',
     '    at connect (net.js:767:19)',
     '    at net.js:846:9',
     '    at dns.js:72:18',
     '    at process._tickDomainCallback (node.js:486:13)' ],
  message: 'connect Unknown system errno 64',
  code: 'Unknown system errno 64',
  errno: 'Unknown system errno 64',
  syscall: 'connect' }
{ domain:
   { domain: [1mnull[22m,
     _events: { error: [36m[Function][39m },
     _maxListeners: [33m10[39m,
     members: [] },
  _events:
   { connect: [36m[Function][39m,
     disconnect: [36m[Function][39m,
     status: [36m[Function][39m,
     error: [36m[Function][39m,
     message: [36m[Function][39m },
  _maxListeners: [33m10[39m,
  id: [32m'2789529a013128ad39ef406ebfc50ecb'[39m,
  friendlyName: [32m'DVC Chromecast'[39m,
  address: [32m'130.217.41.135'[39m,
  port: [33m8009[39m,
  logger:
   { domain: [1mnull[22m,
     _events: {},
     _maxListeners: [33m10[39m,
     padLevels: [33mfalse[39m,
     levels:
      { silly: [33m0[39m,
        debug: [33m1[39m,
        verbose: [33m2[39m,
        info: [33m3[39m,
        warn: [33m4[39m,
        error: [33m5[39m },
     silly: [36m[Function][39m,
     debug: [36m[Function][39m,
     verbose: [36m[Function][39m,
     info: [36m[Function][39m,
     warn: [36m[Function][39m,
     error: [36m[Function][39m,
     level: [33m3[39m,
     emitErrs: [33mfalse[39m,
     stripColors: [33mfalse[39m,
     exitOnError: [33mtrue[39m,
     transports:
      { console:
         { domain: [1mnull[22m,
           _events:
            { error:
               [ [36m[Function][39m,
                 [36m[Function][39m,
                 [36m[Function][39m ] },
           _maxListeners: [33m10[39m,
           level: [32m'debug'[39m,
           silent: [33mfalse[39m,
           raw: [33mfalse[39m,
           name: [32m'console'[39m,
           handleExceptions: [33mtrue[39m,
           json: [33mfalse[39m,
           colorize: [33mtrue[39m,
           prettyPrint: [33mtrue[39m,
           timestamp: [33mfalse[39m,
           label: [1mnull[22m,
           _onError: [36m[Function][39m } },
     rewriters: [],
     exceptionHandlers: {},
     profilers: {},
     _names: [ [32m'console'[39m ],
     _hnames: [],
     catchExceptions: [36m[Function][39m,
     express: { error: [36m[Function][39m, access: [36m[Function][39m },
     exception: [36m[Function][39m,
     colors: [33mfalse[39m,
     enabled: [33mtrue[39m },
  timeout: [33m20000[39m,
  _stopped: [33mfalse[39m,
  _backoff:
   { domain: { [32m'$ref'[39m: [32m'$["domain"]'[39m },
     _events: { ready: [36m[Function][39m, fail: [36m[Function][39m },
     _maxListeners: [33m10[39m,
     backoffStrategy_:
      { initialDelay_: [33m100[39m,
        maxDelay_: [33m10000[39m,
        randomisationFactor_: [33m0.2[39m,
        backoffDelay_: [33m1300[39m,
        nextBackoffDelay_: [33m2100[39m },
     maxNumberOfRetry_: [33m-1[39m,
     backoffNumber_: [33m7[39m,
     backoffDelay_: [33m1525[39m,
     timeoutID_: [33m-1[39m,
     handlers: { backoff: [36m[Function][39m } },
  channel:
   { domain: { [32m'$ref'[39m: [32m'$["domain"]'[39m },
     _events:
      { connect:
         [ { [Function: g] listener: [36m[Function][39m },
           { [Function: g] listener: [36m[Function][39m } ],
        error: [36m[Function][39m,
        disconnect: [36m[Function][39m,
        message: [36m[Function][39m },
     _maxListeners: [33m10[39m,
     logger: { [32m'$ref'[39m: [32m'$["logger"]'[39m },
     name: [32m'sender-2MYNMWJ38M'[39m,
     authenticated: [33mfalse[39m,
     disconnecting: [33mtrue[39m,
     cleanup: [36m[Function: cleanup][39m,
     write: [36m[Function: write][39m },
  _subscriptions:
   [ { channel: [32m'dashkiosk'[39m,
       topic: [32m'group.*.dashboard.*.added'[39m,
       callback:
        { [Function]
          steps: [36m[Function][39m,
          context: [36m[Function][39m,
          before: [36m[Function][39m,
          after: [36m[Function][39m,
          clear: [36m[Function][39m,
          target: [36m[Function][39m } },
     { channel: [32m'dashkiosk'[39m,
       topic: [32m'display.*.group'[39m,
       callback:
        { [Function]
          steps: [36m[Function][39m,
          context: [36m[Function][39m,
          before: [36m[Function][39m,
          after: [36m[Function][39m,
          clear: [36m[Function][39m,
          target: [36m[Function][39m } } ],
  _updateRunning: [33mfalse[39m }

**Comment by vincentbernat** [comment]
Errno 64 is `ENONET`. I suppose this is because some Chromecast was unreachable for some moment. There is no way to suppress this error but the Chromecast should either be rediscovered by mDNS later or if mDNS didn't expire, it should be rediscovered after 2 minutes.

Are you able to tell which Chromecast has the problem and did the Chromecast reappear itself after two minutes? If not, I'll try to reproduce and fix.

**Comment by vincentbernat** [comment]
Old bug, no new info. Feel free to reopen if this issue is still present.
