### ISSUE TITLE
login in a specific URL

### ISSUE THREAD

**Issue by davduke** [vincentbernat/dashkiosk#28]
Hi! I've a doubt. I want to make login in a external URL to see an specific content inside the dashboard. There is a possibility to do that in dashkiosk? or... what could be an easy way to do it?

**Comment by vincentbernat** [comment]
If the login is done by "auth basic", you can just put the credentials in the URL ([http://login:password@internal.example.com/dashboard](http://login:password@internal.example.com/dashboard) for example). If it's a regular HTML form, there is nothing in Dashkiosk to help you autologin (and Dashkiosk is unable to interact with displayed pages as they are subject to cross-origin protection).

**Comment by vincentbernat** [comment]
Nothing much can be done in Dashkiosk.
