### ISSUE TITLE
Chromecast at 1080p

### ISSUE THREAD

**Issue by algiecas** [vincentbernat/dashkiosk#29]
I have dashkiosk up and running and have multiple TVs with Chromecasts. The problem I'm facing is that I can't get to output 1920x1080 to my Full HD TVs even if I manually set the viewport. It shows width/height 1280x720 on TV screen when i click "Show names" icon. And it is the same on different TV models.

Why is this happening and where should I start troubleshooting?

Thanks!

**Comment by vincentbernat** [comment]
As far as I know, a Chromecast cannot output anything else than 720p. The viewport setting is just to emulate a different resolution, but is only effective on mobile devices. The Chromecast will ignore it. You can still use the zoom feature on each dashboard if some dashboard require 1080p.

**Comment by algiecas** [comment]
Chromecast is capable of outputing 1080p (at least it says so here: http://thenextweb.com/google/2014/09/08/googles-chromecast-gets-1080p-chrome-tab-casting-via-beta-extension/)

But probably it's not possible to use that without Chromecast Beta browser extention. Oh well, so long Chromecast...

**Comment by vincentbernat** [comment]
❦ 14 août 2015 05:18 -0700, Algimantas Krasauskas <notifications@github.com> :

> Chromecast is capable of outputing 1080p (at least it says so here:
> http://thenextweb.com/google/2014/09/08/googles-chromecast-gets-1080p-chrome-tab-casting-via-beta-extension/)
>
> But probably it's not possible to use that without Chromecast Beta
> browser extention. Oh well, so long Chromecast...

Maybe only fullscreen video playback is available in 1080p.
-- 
The difference between the right word and the almost right word is the
difference between lightning and the lightning bug.
		-- Mark Twain
