### ISSUE TITLE
Drag'n dropping a dashboard in place duplicates it

### ISSUE THREAD

**Issue by falzm** [vincentbernat/dashkiosk#30]
With the new features of being able to drag'n drop dashboards across groups, what looks like to be a bug is triggered by DnDing a dashboard almost "in place", for example grabbing the line, moving it by a few pixels and releasing: the dashboard line is now duplicated. Is this the expected behavior? I thought DnD would "move" a dashboard to its new destination.

**Comment by vincentbernat** [comment]
Yes, that's the expected behavior. The functionality is copy and duplicate was a side-effect. I did document it this way: http://dashkiosk.readthedocs.org/en/latest/usage.html#groups. Maybe it should be moved unless you press shift and in this case, this will be a copy?

**Comment by falzm** [comment]
OK, sorry for not RTFM.

Feels a bit weird from a UX standing point, since usually in UIs DnDing an item from a location to another moves it. Maybe changing the DnD behavior to *move* the dashboard by default and optionally *copy* it by pressing shift would feel more familiar?

**Comment by vincentbernat** [comment]
Yes, I'll try that

**Comment by vincentbernat** [comment]
I implemented that but unfortunately, a bug in Chromium prevents the distinction between a move and a copy. Therefore, I am using copy in this case as it is more useful than a move. On Firefox, this works just as expected.

**Comment by falzm** [comment]
OK, thanks. Luckily for me I run Firefox ;)

**Comment by vincentbernat** [comment]
Also implemented in Chromium. 2.6.2 with all that has been released.
