### ISSUE TITLE
Restarting loop

### ISSUE THREAD

**Issue by algiecas** [vincentbernat/dashkiosk#31]
I'm using 2.6.2 with bunch of chromecasts. Everything works fine, except some heavy JS pages with multiple charts, etc. Dashkiosk tries to load the page but then does not let it finish loading and restarts (shows "Please wait" receiver screen for a second). And does this infinitely.

I have tried setting Timeout to like 120 seconds, but it does not help.

How can I solve this? Thanks!

**Comment by vincentbernat** [comment]
❦ 22 septembre 2015 09:08 -0700, Algimantas Krasauskas <notifications@github.com> :

> I'm using 2.6.2 with bunch of chromecasts. Everything works fine,
> except some heavy JS pages with multiple charts, etc. Dashkiosk tries
> to load the page but then does not let it finish loading and restarts
> (shows "Please wait" receiver screen for a second). And does this
> infinitely.
>
> I have tried setting Timeout to like 120 seconds, but it does not
> help.
>
> How can I solve this? Thanks!

If you get the "Please wait" receiver, it may mean that the Chromecast
has stopped responding. Maybe looking at the logs of Dashkiosk would
help to know who takes the decision to restart the Chromecast receiver.
-- 
Don't sacrifice clarity for small gains in "efficiency".
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by algiecas** [comment]
Logs say ```Chromecast device is NOT on home screen``` then ```display disconnected```

Log (omitting url):
>{"protocol_version":0,"source_id":"Tr@n$p0rt-0","destination_id":"Tr@n$p0rt-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":0,"payload_utf8":"{\"type\":\"PING\"}","payload_binary":null,"level":"debug","message":"Received from Chromecast","timestamp":"2015-09-22T16:46:12.154Z"}
{"protocol_version":0,"source_id":"Tr@n$p0rt-0","destination_id":"Tr@n$p0rt-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":"STRING","payload_utf8":"{\"type\":\"PONG\"}","payload_binary":null,"level":"debug","message":"Sent to Chromecast","timestamp":"2015-09-22T16:46:12.155Z"}
{"protocol_version":0,"source_id":"Tr@n$p0rt-0","destination_id":"Tr@n$p0rt-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":0,"payload_utf8":"{\"type\":\"PING\"}","payload_binary":null,"level":"debug","message":"Received from Chromecast","timestamp":"2015-09-22T16:46:12.307Z"}
{"protocol_version":0,"source_id":"Tr@n$p0rt-0","destination_id":"Tr@n$p0rt-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":"STRING","payload_utf8":"{\"type\":\"PONG\"}","payload_binary":null,"level":"debug","message":"Sent to Chromecast","timestamp":"2015-09-22T16:46:12.307Z"}
{"protocol_version":0,"source_id":"receiver-0","destination_id":"*","namespace":"urn:x-cast:com.google.cast.receiver","payload_type":0,"payload_utf8":"{\"requestId\":0,\"status\":{\"applications\":[{\"appId\":\"5E7A2C2C\",\"displayName\":\"Dashkiosk Chromecast receiver\",\"namespaces\":[{\"name\":\"urn:x-cast:com.deezer.cast.dashkiosk\"}],\"sessionId\":\"B27BD018-F34D-425E-B4A6-E8A0CEA08AA9\",\"statusText\":\"Receiver: http://10.10.30.10:9404/receiver#register=951gVSF/N6Im/GHv+OY/CliyIhqbO6V9bJobQoz4vzo=|1442939775|50nUIeJR7hzU7g==|TPEf4i4XbiXY7nUBNewiJw==|/zIgwx20VMsSl+ucKQm8qizR//C/wL8qPTG/CrpJxwSjQUeKLeX1JUVXnnzGmodEvua6jRzCFgRR3cBLt20Wcg==\",\"transportId\":\"web-2\"}],\"isActiveInput\":true,\"isStandBy\":false,\"volume\":{\"level\":1.0,\"muted\":false}},\"type\":\"RECEIVER_STATUS\"}","payload_binary":null,"level":"debug","message":"Received from Chromecast","timestamp":"2015-09-22T16:46:12.980Z"}
{"id":"28fe31a11cb7b06dd95417fcb569a73c","chromecast":"40\" Kairys","level":"debug","message":"Chromecast device is NOT on home screen","timestamp":"2015-09-22T16:46:12.981Z"}
{"level":"info","message":"display disconnected WKLXS4","timestamp":"2015-09-22T16:46:15.039Z"}
{"level":"debug","message":"Executing (default): SELECT * FROM `Displays` WHERE `Displays`.`id`=1 LIMIT 1;","timestamp":"2015-09-22T16:46:15.040Z"}
{"level":"info","message":"new display 10.10.30.141","timestamp":"2015-09-22T16:46:17.175Z"}
{"level":"debug","message":"Executing (default): SELECT * FROM `Displays` WHERE `Displays`.`name`='WKLXS4' LIMIT 1;","timestamp":"2015-09-22T16:46:17.388Z"}
{"level":"info","message":"registered display WKLXS4 undefined","timestamp":"2015-09-22T16:46:17.389Z"}
{"client":"WKLXS4","dashboard":{"id":7,"url":"........","description":null,"timeout":null,"viewport":null,"delay":null,"availability":null,"group":7,"active":true},"level":"info","message":"specific dashboard for display","timestamp":"2015-09-22T16:46:17.390Z"}
{"level":"debug","message":"Executing (default): UPDATE `Displays` SET `id`=1,`name`='WKLXS4',`description`='40\" Kairys',`chromecast`='28fe31a11cb7b06dd95417fcb569a73c',`viewport`=NULL,`createdAt`='2015-09-22 14:44:00.000 +00:00',`updatedAt`='2015-09-22 16:46:17.000 +00:00',`GroupId`=7 WHERE `id`=1","timestamp":"2015-09-22T16:46:17.391Z"}
{"protocol_version":0,"source_id":"sender-1F4YQ7AUUM","destination_id":"receiver-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":"STRING","payload_utf8":"{\"type\":\"PING\"}","payload_binary":null,"level":"debug","message":"Sent to Chromecast","timestamp":"2015-09-22T16:46:26.745Z"}
{"protocol_version":0,"source_id":"receiver-0","destination_id":"sender-1F4YQ7AUUM","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":0,"payload_utf8":"{\"type\":\"PONG\"}","payload_binary":null,"level":"debug","message":"Received from Chromecast","timestamp":"2015-09-22T16:46:26.750Z"}
{"protocol_version":0,"source_id":"sender-1Z8IK4WEPG","destination_id":"receiver-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":"STRING","payload_utf8":"{\"type\":\"PING\"}","payload_binary":null,"level":"debug","message":"Sent to Chromecast","timestamp":"2015-09-22T16:46:26.783Z"}
{"protocol_version":0,"source_id":"receiver-0","destination_id":"sender-1Z8IK4WEPG","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","payload_type":0,"payload_utf8":"{\"type\":\"PONG\"}","payload_binary":null,"level":"debug","message":"Received from Chromecast","timestamp":"2015-09-22T16:46:26.789Z"}

**Comment by vincentbernat** [comment]
When you say the "please wait" screen, you mean this one: https://vincentbernat.github.io/dashkiosk/chromecast.html ?

The disconnected message that you spot is the socket.io connection. When this connection breaks, Dashkiosk will switch to the rotating gear screen (not the screen above). The screen above can only appear when the Chromecast app starts. Since there is nothing in the logs about Dashkiosk requesting a restart of the Chromecast, I would assume that the Chromecast considered the application to have crash and therefore restarted it.

**Comment by algiecas** [comment]
Yeah, it shows this "please wait" screen for a few moments, then "pulsatory" circle which lags badly. Then briefly shows the dashboard site and again "please wait".

So are you saying that Chromecast can't handle the dashboard site?

**Comment by vincentbernat** [comment]
Yes, the "application" is restarted without Dashkiosk asking for it. So I suppose that the Chromecast considers it unresponsive. As it is only a simple webpage embedding the dashboard, I don't see how to workaround that.

Maybe, could you locate the loading-default.svg (with whatever hash number there is) and remove both circles from it:

```
<!-- By Sam Herbert (@sherb), for everyone. More @ http://goo.gl/7AJzbL -->
<svg width="44" height="44" viewBox="0 0 44 44" xmlns="http://www.w3.org/2000/svg" stroke="#fff">
    <g fill="none" fill-rule="evenodd" stroke-width="2">
    </g>
</svg>
```

This is the "pulsatory" circles. Tell me if it improves the situation. If yes, I will disable the animation.

**Comment by algiecas** [comment]
No, unfortunately it didn't help. 

Strange thing is that the page loads once I drag & drop to load some other page and drop back. And only after a while when charts inside dashboard start reloading (some JS activity), it crashes and starts restarting without being able to load it anymore.

Also the page loads fine using this: https://boombatower.github.io/chromecast-dashboard/sender/

So I assume that there still is some problem with Dashkiosk. Not sure if possible to dig it out...

**Comment by vincentbernat** [comment]
If you provide the serial number of your Chromecast, I can add it to my account so that you can enable debug on it. You will be able to see the developer tools while the application is running. Maybe there would be some hint in the console.

A notable difference is that during the transition from one dashboard to another, the two dashboards are loaded in an iframe (the old one which is currently displayed and the new one which is about to be displayed). This is to display the dashboard only when it is ready (this doesn't quite work with javascript generated dashboards, hence the delay option). Having two heavy weight dashboard at the same time may put too much stress on the Chromecast.

**Comment by algiecas** [comment]
Yeah, well, I tried to do this myself, I have created the application (pointing to https://vincentbernat.github.io/dashkiosk/chromecast.html) and launched dashkiosk with ```--chromecast.app 79F4491B``` with no luck. Log says

>error: Unable to find Dashkiosk application 
{ stack: 
   [ 'Error: requested application is not available',
     '    at /Users/macuser/Documents/dashkiosk-2.6.2/dist/node_modules/nodecastor/lib/device.js:134:14',
     '    at CastChannel.answer (/Users/macuser/Documents/dashkiosk-2.6.2/dist/node_modules/nodecastor/lib/channel.js:219:9)',
     '    at CastChannel.emit (events.js:117:20)',
     '    at CleartextStream.readable (/Users/macuser/Documents/dashkiosk-2.6.2/dist/node_modules/nodecastor/lib/channel.js:124:10)',
     '    at CleartextStream.emit (events.js:92:17)',
     '    at emitReadable_ (_stream_readable.js:427:10)',
     '    at _stream_readable.js:420:7',
     '    at process._tickDomainCallback (node.js:492:13)' ],
  message: 'requested application is not available' }

**Comment by vincentbernat** [comment]
Did you try to reboot the Chromecast once it has been successfully registered as a dev Chromecast?

**Comment by vincentbernat** [comment]
This is only needed for unpublished app. If you published the app, it should start as expected. You still need to register the Chromecast to be able to debug the app.

**Comment by vincentbernat** [comment]
Also, about the modified SVG, just to be sure (because this resource is normally cached and maybe the cache was not refreshed): after the modification, there is no more "pulsatory" circles, right?

**Comment by algiecas** [comment]
No circles.

**Comment by algiecas** [comment]
OK, so I managed to run my chromecast app (I guess restart helped). When i go to 9222, I see link "Remote Debugging (AppEngine)". Clicking it opens devtools and nothing is happening there. In the meantime dashkiosk is trying to show the dashboard, restarting, showing, restarting, etc.

**Comment by algiecas** [comment]
Never mind, there was this "shield" thing in the url bar.

**Comment by vincentbernat** [comment]
OK, just to be sure that Dashkiosk is not trying to restart the dashboard. Could you try to disable Chromecast support in Dashkiosk and load the application with:

```
./node_modules/nodecastor/bin/chromecast dashkiosk 192.168.xx.xx http://url-to-dashkiosk/receiver
```

**Comment by algiecas** [comment]
So the console log says ```[Dashkiosk/Device] Heartbeat missed, reload```

>[Dashkiosk/Device] Asked to display URL http://10.10.30.10:9430/receiver#register=5ZlKTZiFVsCnzeoT1aLuICXEv+LPIxt6e…9NdUqM04lf+hkSQFiN0ofEjnfEeLBn1oH3m8mxFjgq1+RqKbrUREkI9MEaj/KNeT28jE5KRQ==
2719fb28.chromecast-final.js:1 [Dashkiosk/Device] Heartbeat received
ea6ba824.receiver-final.js:1 [Dashkiosk] Benchmark: 6 fps
ea6ba824.receiver-final.js:1 [Dashkiosk] Send heartbeat to supervisor
ea6ba824.receiver-final.js:1 [Dashkiosk] dashkiosk ready, connect to socket.io server
2719fb28.chromecast-final.js:1 [Dashkiosk/Device] Heartbeat received
ea6ba824.receiver-final.js:1 [Dashkiosk] connected to socket.io server
ea6ba824.receiver-final.js:1 [Dashkiosk] registered to server
ea6ba824.receiver-final.js:1 [Dashkiosk] viewport change to default requested
ea6ba824.receiver-final.js:1 [Dashkiosk] should display dashboard http://<...>
ea6ba824.receiver-final.js:1 [Dashkiosk] iframe ready http://<...>
ea6ba824.receiver-final.js:1 [Dashkiosk] Send heartbeat to supervisor
2719fb28.chromecast-final.js:1 [Dashkiosk/Device] Heartbeat missed, reload
2719fb28.chromecast-final.js:1 [Dashkiosk/Device] Asked to display URL http://10.10.30.10:9430/receiver#register=5ZlKTZiFVsCnzeoT1aLuICXEv+LPIxt6e…9NdUqM04lf+hkSQFiN0ofEjnfEeLBn1oH3m8mxFjgq1+RqKbrUREkI9MEaj/KNeT28jE5KRQ==
2719fb28.chromecast-final.js:1 [Dashkiosk/Device] Heartbeat received
ea6ba824.receiver-final.js:1 [Dashkiosk] Benchmark: 6 fps
ea6ba824.receiver-final.js:1 [Dashkiosk] Send heartbeat to supervisor
ea6ba824.receiver-final.js:1 [Dashkiosk] dashkiosk ready, connect to socket.io server
2719fb28.chromecast-final.js:1 [Dashkiosk/Device] Heartbeat received
ea6ba824.receiver-final.js:1 [Dashkiosk] connected to socket.io server
ea6ba824.receiver-final.js:1 [Dashkiosk] registered to server
ea6ba824.receiver-final.js:1 [Dashkiosk] viewport change to default requested
ea6ba824.receiver-final.js:1 [Dashkiosk] should display dashboard http://<...>
ea6ba824.receiver-final.js:1 [Dashkiosk] iframe ready http://<...>
ea6ba824.receiver-final.js:1 [Dashkiosk] Send heartbeat to supervisor
2719fb28.chromecast-final.js:1 [Dashkiosk/Device] Heartbeat missed, reload

**Comment by vincentbernat** [comment]
Oh, right. Sorry. I didn't remember there was an heartbeat at this level of the application. It is however quite large (30 seconds). For example, how much time elapses between the before last line and the last line? It should elapse about 6 seconds. This would mean that the messaging system is not reliable.

In `app/scripts/receiver/supervisor.js`, you can change `0.8` to `0.2` to send those hearbeat messages more often and see if this fixes the problem (if you want to change the minified files directly, this is in `receiver-final.js`, search for `,.8`.

**Comment by algiecas** [comment]
Didn't quite understand about elapsed timeouts, but changing ```.8``` to ```.2``` seems to do the trick. Dashboard is running without problems for several hours.

Thanks! :)

**Comment by vincentbernat** [comment]
The hearbeat should have happened every 24 seconds. And the supervisor was expecting them in less than 30 seconds. 6 seconds of lag seemed plenty but either some heartbeats are lost (but as far as I know, the method used to send heartbeats should reliably deliver them) or they were delayed for more than 6 seconds.

Anyway, I'll change to 0.2 for future releases.
