### ISSUE TITLE
Will this run on OSX? Sorry if it's a lame question...

### ISSUE THREAD

**Issue by davidcatherall** [vincentbernat/dashkiosk#32]
Hi, I'm wanting to get stuck into this - Tried Groupons Greenscreen but failed to get it up and running.  Purchased a Mac mini to run it on, so - I'm guessing, after reading through the docs that it's predominantly Linux that this was designed for... before I get stuck-in what is the recommended platform?  Any particular distro of Linux or shall I continue with OSX?

**Comment by plitewaikato** [comment]
I'm running it on OS X.  Works fine.

**Comment by vincentbernat** [comment]
I am developing it on Linux, but I am happy to see it works on OS X. Any bug on OS X will be considered as any other bug.

**Comment by davidcatherall** [comment]
Many Thanks!
