### ISSUE TITLE
Chromecast attempts to connect to http://dashkiosk:9400/reciever

### ISSUE THREAD

**Issue by rickardl** [vincentbernat/dashkiosk#34]
I'm having some issues with one of my installations since upgrading to 2.4.6, it seems like the chromecasts are getting stuck attempting to connect to a reciever at http://dashkiosk:9400, since the Chromecast only listens on Google DNS servers, I can't make it go to my local url. (I checked this through the Google Cast Debugger)

```
node server.js --port 9400 --environment production --chromecast.enabled --chromecast.app "4E937438" --chromecast.receiver "http://10.0.1.146:9400/receiver"
```

I see that there's a default in chromecast.js

``` js
  function receiverUrl() {
    var url = config.get('chromecast:receiver') || (function() {
      return 'http://dashkiosk:' + config.get('port') + '/receiver';
    })();
    if (!(/^https?:\/\//.test(url))) {
      logger.warn('Receiver URL should be a fully qualified URL!');
      url = 'http://' + url;
    }
    return url;
  }
```

It's really strange...

**Comment by vincentbernat** [comment]
I just tested myself and the receiver seems to be correct. However, I agree that there is something odd in your case. If you replace the third line with your IP address directly, does it work?

```js
 function receiverUrl() {
    var url = config.get('chromecast:receiver') || (function() {
      return 'http://10.0.1.146:' + config.get('port') + '/receiver';
    })();
    if (!(/^https?:\/\//.test(url))) {
      logger.warn('Receiver URL should be a fully qualified URL!');
      url = 'http://' + url;
    }
    return url;
  }
```

If this works, it means that the configuration is somehow incorrect. In this case, could you add `console.log(config.get())` at the top of the function? And see if there is anything from your configuration?

**Comment by rickardl** [comment]
Hi Vincent!

I tried that myself, and it seems to do the job, maybe there should be an error message when it reaches that point, since it will fail.

Thank you for a speedy reply, I'll investigate why my configuration might be be misconfigured and post the results here. You've done a really good job at this.

**Comment by vincentbernat** [comment]
Yes, using "dashkiosk" is a bit useless. Initially, I wanted to put the local IP but the clean way to do this is unavailable with node (connecting to an IP with an UDP socket and reading the source address). Other ways to do that are system-specific (looking at the route table for example).

I'll wait for you to find why `config.get('chromecast:receiver')` returns `null` and we'll try to fix that correctly.

**Comment by vincentbernat** [comment]
I have pushed 45421434f866. This shouldn't fix your problem but will make the error more explicit when it is missing.

**Comment by rickardl** [comment]
Thank you!

**Comment by vincentbernat** [comment]
Does the problem still exist or was it just a configuration problem on your side? I'll close the issue in the meantime. Reopen if this is still an issue.
