### ISSUE TITLE
Failed to find SQL server.

### ISSUE THREAD

**Issue by charleshetzel** [vincentbernat/dashkiosk#38]
Good afternoon,

I'm sure this is a really simple/silly issue, but I just don't have the knowledge on SQL as of yet. I'm fairly certain I've gotten all the steps correctly completed, but I cannot get a SQLite DB to be created for the life of me. Any help is appreciated. 

2016-01-07T19:50:40.545Z - error: uncaughtException: Uncaught, unspecified "error" event. (Failed to find SQL server. Please double check your settings.) 
{ date: 'Thu Jan 07 2016 14:50:40 GMT-0500 (EST)',
  process: 
   { pid: 1573,
     uid: 501,
     gid: 20,
     cwd: '/Users/admin/Desktop/dashkiosk-master/dist',
     execPath: '/usr/local/bin/node',
     version: 'v5.1.1',
     argv: 
      [ '/usr/local/bin/node',
        '/Users/admin/Desktop/dashkiosk-master/dist/server.js',
        '--environment',
        'production' ],
     memoryUsage: { rss: 66772992, heapTotal: 59120896, heapUsed: 32351088 } },
  os: 
   { loadavg: [ 0.7548828125, 0.9775390625, 1.0478515625 ],
     uptime: 1089 },
  trace: 
   [ { column: 17,
       file: 'events.js',
       function: 'EventEmitter.emit',
       line: 144,
       method: 'emit',
       native: false },
     { column: 19,
       file: '/Users/admin/Desktop/dashkiosk-master/dist/node_modules/sequelize/lib/dialects/sqlite/connector-manager.js',
       function: '',
       line: 27,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: Uncaught, unspecified "error" event. (Failed to find SQL server. Please double check your settings.)',
     '    at EventEmitter.emit (events.js:144:17)',
     '    at Database.<anonymous> (/Users/admin/Desktop/dashkiosk-master/dist/node_modules/sequelize/lib/dialects/sqlite/connector-manager.js:27:19)' ] }
hs-126-test:dist admin$ node server.js --environment production
2016-01-07T19:54:35.208Z - error: uncaughtException: Uncaught, unspecified "error" event. (Failed to find SQL server. Please double check your settings.) 
{ date: 'Thu Jan 07 2016 14:54:35 GMT-0500 (EST)',
  process: 
   { pid: 1822,
     uid: 501,
     gid: 20,
     cwd: '/Users/admin/Desktop/dashkiosk-master/dist',
     execPath: '/usr/local/bin/node',
     version: 'v5.1.1',
     argv: 
      [ '/usr/local/bin/node',
        '/Users/admin/Desktop/dashkiosk-master/dist/server.js',
        '--environment',
        'production' ],
     memoryUsage: { rss: 67084288, heapTotal: 59120896, heapUsed: 32563648 } },
  os: 
   { loadavg: [ 1.0283203125, 1.01806640625, 1.04248046875 ],
     uptime: 1324 },
  trace: 
   [ { column: 17,
       file: 'events.js',
       function: 'EventEmitter.emit',
       line: 144,
       method: 'emit',
       native: false },
     { column: 19,
       file: '/Users/admin/Desktop/dashkiosk-master/dist/node_modules/sequelize/lib/dialects/sqlite/connector-manager.js',
       function: '',
       line: 27,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: Uncaught, unspecified "error" event. (Failed to find SQL server. Please double check your settings.)',
     '    at EventEmitter.emit (events.js:144:17)',
     '    at Database.<anonymous> (/Users/admin/Desktop/dashkiosk-master/dist/node_modules/sequelize/lib/dialects/sqlite/connector-manager.js:27:19)' ] }

Thanks!

**Comment by charleshetzel** [comment]
Disregard. I got it. I only had read permissions to the dist folder. Knew it was a simple fix.

Thanks!

**Comment by vincentbernat** [comment]
Good to know, I wouldn't have been able to suggest anything! :)
