### ISSUE TITLE
Movie freezing intermittently

### ISSUE THREAD

**Issue by computermedic** [vincentbernat/dashkiosk#46]
Hello,
Unfortunately, I do not have any logs at the moment to share, however our locally hosted movie(s) freeze intermittently when being streamed to a chromecast. Usually it happens in the transition from one movie to the other. It has been tested on two different chromecasts in 2 differrent network locations. The video(s) are in .mp4 format and everything works okay but I would say once a day this happens. 
What I have tried:
1. Adding individual movie urls (locally hosted) to a group will freeze instantly between the transition between the two movies.
2. Movies are re-converted into the proper format and movies will play through maybe once or twice in the group then freeze.
3. We have tried to manage apache to control the movie looping, it worked but once a day the proper exists.
4. We have taken all the movies and "joined" them into 1 .mp4 and the movie will still freeze in what appears to be the transition between the two.

My guess: One of the .mp4s are in the wrong format for the Chromecast. Other than that, do you have any advice or any fixes to handle movies freezing?

Thank you for all of your efforts and I deeply enjoy this software.

Regards

**Comment by vincentbernat** [comment]
Not much we can do. Due to the way transitions work, the two movies are playing at the same time during transition. I suppose that the Chromecast cannot handle that correctly. One solution would be to add a "about:blank" URL (or something like that) between each transition to avoid to transition from one movie to another.

**Comment by vincentbernat** [comment]
Not much can be done about the limitations of the Chromecast. A more viable option is to use an Android key. The price is almost the same and they have far much horse power. I prefer to close this issue for now as there is no immediate action available.
