### ISSUE TITLE
always dev-mode despite enviroment

### ISSUE THREAD

**Issue by Deph0** [vincentbernat/dashkiosk#48]
Hi, I'm having issues with getting this to start in production mode rather then developement mode.
run command: ```../dist/& node server.js --port 9400 --environment production --chromecast.enabled --chromecast.receiver "http://vmip:9400/receiver" ```

I'm using a nodeJs OVH image from Bitnami (https://bitnami.com/stack/nodejs/virtual-machine)

using the vm, having to install some dependencies first
```sudo apt-get install libavahi-compat-libdnssd-dev libsqlite3-dev (and sqlite3?)``` as well as ```npm install grunt-mocha-test mocha``` before running ```npm install && grunt```

**Comment by vincentbernat** [comment]
Is there an error message?

**Comment by Deph0** [comment]
None that i can see.

On 15 Oct, 2016, at 12:32 PM, Vincent Bernat <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there an error message?

**Comment by vincentbernat** [comment]
So, it doesn't start but says nothing?

**Comment by Deph0** [comment]
Not that i can see- I can’t scroll up in the terminal and it doesnt appear to write anything useful into stdout so piping it into a file doesnt do me much.

On 15 Oct, 2016, at 12:52 PM, Vincent Bernat <notifications@github.com<mailto:notifications@github.com>> wrote:


So, it doesn't start but says nothing?

**Comment by vincentbernat** [comment]
Sorry, I have a hard time understanding the problem. There is little difference between dev and production environment. What's "dev-mode" for you?

**Comment by Deph0** [comment]
I think it’s odd that i can’t get out of development mode wihen telling it to start with production environment. what exactly is the difference?
Does Chromecast still work in development mode without having a custom receiver that would require an chromecast SDK fee ?

On 15 Oct, 2016, at 8:37 PM, Vincent Bernat <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I have a hard time understanding the problem. There is little difference between dev and production environment. What's "dev-mode" for you?

**Comment by vincentbernat** [comment]
There is no difference between environments for the chromecast.

**Comment by Deph0** [comment]
Aha.. well ok- i might have found my issue, bitnami wants me to pass ports with proxy thu apache..

```ProxyPass / http://localhost:9400/
ProxyPassReverse / http://localhost:9400/
```
this makes it to the dashkiosk start script but renders '404 cannot GET /receiver’ in browser :\

any ideas on how to proxy this correctly?

ref; https://docs.bitnami.com/google/infrastructure/nodejs/#how-to-create-a-custom-nodejs-application

On 15 Oct, 2016, at 8:53 PM, Vincent Bernat <notifications@github.com<mailto:notifications@github.com>> wrote:


There is no difference between environments for the chromecast.

**Comment by Deph0** [comment]
I'm sorry for this convoluted issue.
I finally found their FAQ about opening up the firewall; `$ sudo ufw allow 9400`
 however my problem now still stands with everything just getting 404'd with dashkiosk printing out the http request and returning 'could not GET /receiver' 

ref; https://docs.bitnami.com/virtual-machine/faq/#how-to-configure-the-firewall

**Comment by vincentbernat** [comment]
Does `dist/public/receiver.html` exists? In your first post, the command you use is dubious. Are you sure the beginning is `../dist/&`? It means execute dist in the background. It should be `cd dist && node ...`.

Also note that if you are interested in Chromecast support, it is unlikely to work if Dashkiosk doesn't run in the same network than Chromecasts.

**Comment by Deph0** [comment]
yes- sorry. the ``../dist/&`` is a typo where & should have been $ and it was a attempt on showing that i am in the correct folder, dist when running ``node server.js``

the receiver.html file exists and shows up when i do ``http://vmip:9400/public/receiver.html/`` in my browser.

**Comment by vincentbernat** [comment]
That's odd that the URL `/public/receiver.html` works. It shouldn't work in either production or dev mode. What is the result of `curl -v http://vmip:9400/receiver`?

**Comment by Deph0** [comment]
`$ curl -v http://vmip:9400/receiver
*   Trying vmip...
* Connected to vmip (vmip) port 9400 (#0)
> GET /receiver HTTP/1.1
> Host: vmip:9400
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 21
< Date: Tue, 18 Oct 2016 06:13:04 GMT
< Connection: keep-alive
< 
Cannot GET /receiver
* Connection #0 to host vmip left intact`

I should clearify that the ``/public/receiver.html`` did show up as a normal webpage, but couldnt interact with it, as everything said error, could not sql or something like that. I don't know what changed but that doesn't appear to work now.

**Comment by vincentbernat** [comment]
When you run Dashkiosk, it should "Express server listening on port 9400 in production mode". Is that the case?

**Comment by Deph0** [comment]
It says that but in development mode.

**Comment by vincentbernat** [comment]
Do you have a `config.json` around? If yes, does it have another environment set? Also, before starting dashkiosk, check what's the result of `env | grep -i env`.

**Comment by Deph0** [comment]
Unless dashkiosk generated a config somewhere that i dont see, there is no config.json. 
env returned `_=/usr/bin/env` is that normal? i don't know.

**Comment by vincentbernat** [comment]
The `config.json` would be in the same directory. The returned value for `env | grep -i env` is correct.

I don't see what the problem could be `node server.js --environment production` should display `in production mode`. You can try to modify `dist/lib/config.js`, line 16 and replace `|| 'development'` by `|| 'production'`.

**Comment by Deph0** [comment]
Ah, awesome. That did the trick to get it into production mode, and everything now automagically works like it should. 👍

**Comment by vincentbernat** [comment]
That's still quite odd. Are you sure you didn't mispelled `--environment`?

**Comment by Deph0** [comment]
Well you got me there, I'm bamboozled and shocked. I must have retyped that a hundred times to make sure i wasn't just doing it wrong. I have retyped environment without the N every damn time. *facepalm* https://www.youtube.com/watch?v=BNsrK6P9QvI

**Comment by Deph0** [comment]
I think we all can agree on that I'm a floating blob and sometimes life doesn't want you to succeed. Put down the fires, false alarm- there is no dragon coming to eat your babies.

**Comment by vincentbernat** [comment]
Well, that's good to know (that there is no bug)! ;-)
