### ISSUE TITLE
Cast and setMediaPlaybackRequiresUserGesture

### ISSUE THREAD

**Issue by letic** [vincentbernat/dashkiosk#51]
Hello Vincent,

I was trying to deploy dashkiosk in our company but hit a few snag. We have nexus players with cast enabled. Everything is working great except for videos.

They do not autoplay as it seems the Nexus Player must have the setMediaPlaybackRequiresUserGesture set to true.

We tried doing a JS hack (simulate press on play) but it doesn't work on video hosted on separate domains. Do you think this can still be done that way ?

It does work with the Android application but it seems a lot slower than through Cast and it display continuously the DashKiosk logo and top bar overlay.

Can you confirm that if we buy Chromecast they will autoplay video ?

Thanks in advance !
Anthony

**Comment by vincentbernat** [comment]
I didn't test the Chromecast since quite some time. When I tested, autoplay of Youtube video was working, but this could have been changed. I am a bit uncomfortable to confirm anything (Chromecast have other reliability problems with Dashkiosk).

A workaround for the origin problem (with your JS hack) is to serve the content through a proxy, so that it appears to come from the same domain.

As for the Android app, the bar should hide after a few seconds. Which Android version do you have?

**Comment by letic** [comment]
They are Nexus Player so they are using Android 7 Nougat. I found the issue it was just the fact that by default the lock screen option wasn't set. Once set the top bar disappeared.

Now it would be perfect if I could get it to run on boot. Have you implemented an Android service in the Dashkiosk Android application ?

Thanks for your reactivity. It's much appreciated.
Anthony

**Comment by letic** [comment]
It seems only DailyMotion videos are working in autoplay in the app. Neither Youtube nor Vimeo videos are playing either.

I am investigating if Xwalk are setting the setMediaPlaybackRequiresUserGesture as well.

Anthony

**Comment by vincentbernat** [comment]
Thanks. Updating Xwalk would also be possible if needed.

**Comment by letic** [comment]
Thanks Vincent for the pointers. 

To reply to you I do see the Home replacement in the simulator in Android TV 5 but it doesn't seems to work anymore on Android TV 7. I will try to investigate later.

Secondly I tried several tricks to force the autoplay in the app to no avail.

I upgraded xwalk to the latest version (21) which broke the autoplay of dailymotion as well. I tried setting the flag discussed previously but it is not available on a XWalkView in getSettings. 

I checked the code and the forum and It is not implemented. Weird because this [guy](https://github.com/tekinarslan/CrosswalkWebview/blob/master/app/src/main/java/com/tekinarslan/crosswalkwebview/MainActivity.java) had some code using it.

XWalk developers details that we can pass flags via [xwalk command line](https://lists.crosswalk-project.org/pipermail/crosswalk-help/2015-August/001401.html). So I created an assets directory and put the file containing only "xwalk --disable-gesture-requirement-for-media-playback" as requested. But even after building a new apk it still doesn't work.

So I am a bit at loss to be honest. Dashkiosk would be useless for us without the ability to run video. Any ideas ?

Thanks a lot in advance
Anthony

**Comment by letic** [comment]
I also tried the following code in the DashboardActivity.java (trying to put it as early as possible) : 

`static final String INIT_SWITCHES[] = { "Xwalk", "--disable-gesture-requirement-for-media-playback"  };
    public static final String COMMAND_LINE_FILE = "/data/local/tmp/xwview-shell-command-line";
    @Override
    public void onCreate(Bundle savedInstanceState) {
        if (!CommandLine.isInitialized()) {
            CommandLine.init(INIT_SWITCHES);
        }

        if (!CommandLine.isInitialized()) {
            CommandLine.initFromFile(COMMAND_LINE_FILE);
        }

        super.onCreate(savedInstanceState);`

As some people were saying that the [file method](https://lists.crosswalk-project.org/pipermail/crosswalk-help/2015-July/001333.html) does not work.

But still no luck...

Anthony

**Comment by vincentbernat** [comment]
I didn't know about the command line switches.

Looking at the documentation for API v7, I don't see anything related to this. However, in the code source, XWalkSettings should expose [setMediaPlaybackRequiresUserGesture](https://github.com/crosswalk-project/crosswalk/blob/e3259b966dcedd18dc456b8cc97cd1a52aad58ea/runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java#L862). There is a [JIRA issue](https://crosswalk-project.org/jira/browse/XWALK-4395) that talks about implementing access to it but unfortunately, the actual committed code doesn't seem to match the request. I have added a comment about this.

**Comment by vincentbernat** [comment]
Another thought: as it was working with Crosswalk 16 with Dailymotion and it stopped working, maybe you could stick with this version and investigate why Youtube doesn't autoplay. Do you use the iframe URL?

**Comment by letic** [comment]
Thanks Vincent,

I actually checked and the Dailymotion video is only working on the actual Nexus and not in the simulator. Weird.

Yes URLs are correct, I am using the embed links with the autoplay flags and it is working fine with all browsers but not in the Android app or through cast.

Samples used : 
Dailymotion : http://www.dailymotion.com/embed/video/xygqh6?autoplay=1 (from your tutorial)
Vimeo : https://player.vimeo.com/video/1084537?autoplay=1
Youtube : https://www.youtube.com/embed/18XdSvZptlc?&autoplay=1

I already saw this JIRA issue but actually looking at the recent activity I saw a pointer to [XWALK-6853](https://crosswalk-project.org/jira/browse/XWALK-6853) which actually does expose the get/setMedia... methods!

It is implemented in version 22 which is not supposed to be released. So I used this version and the good news is that I can call getSettings().setMediaPlaybackRequiresUserGesture(false);

Unfortunately the bad news is that it doesn't affect the behaviour at all...

I will make a PR so you can see the small changes I made to upgrade to the new version of XWalk to no avail yet. Maybe this is due to the fact that they are loaded in iframes ? What do you think ?

Thanks a lot for your help
Anthony

**Comment by letic** [comment]
See https://github.com/vincentbernat/dashkiosk-android/pull/3

**Comment by vincentbernat** [comment]
Let's followup this bug in vincentbernat/dashkiosk-android#3.
