### ISSUE TITLE
Raspberry Pi 3 jessie lite / pixel

### ISSUE THREAD

**Issue by Deph0** [vincentbernat/dashkiosk#52]
Hello again- been trying to migrate to a raspberry pi 3 instead of that virtual machine (diff sub-network, blabla chromecast wont work, etc).

been having troubles with getting past the initial 'npm install' where it gets caught on the post-install script.

I have a npm-debug.log file here: http://pastebin.com/m3zWPrCE

I've seen some errors about jpegtran, optipng and gifsicle- however i found the package 'libjpeg-progs' as suggested in previous issues by others, and installed that, without any noticeable differences.

I installed 'libavahi-compat-libdnssd-dev' aswell.

I'm not sure what else to do, does the log file tell you anything?

**Comment by vincentbernat** [comment]
It seems that you didn't copy a clean tree to the Raspberry Pi. Therefore, the build process is confused about the change of architecture.

**Comment by Deph0** [comment]
i used the latest release zip to install, not copy from previous instance.

**Comment by Deph0** [comment]
No idea what changed, other then me deleting the folder and redoing everything (again and again), but suddenly the initial npm install was successful.

**Comment by vincentbernat** [comment]
Can't explain it either. This build process is quite gruesome, notably the image minimization. Maybe making this step optional would help (myself, I often delete node_modules directory to fix things).

**Comment by vincentbernat** [comment]
It seems related to https://github.com/npm/npm/issues/14042. Which is your version of npm now?

**Comment by Deph0** [comment]
I installed the latest, 7.2.0 with https://deb.nodesource.com/setup_7.x repo
