### ISSUE TITLE
node server.js --help → exception

### ISSUE THREAD

**Issue by JulienPalard** [vincentbernat/dashkiosk#54]
Hi,

On a fresh install of dashkiosk `2.7.2`, I tried `--help` but I got:

```
  stack: 
   [ 'Error: ENOENT: no such file or directory, scandir \'/usr/local/src/dashkiosk/dashkiosk-2.7.2/dist/build/images/unassigned\'',
     '    at Error (native)',
     '    at Object.fs.readdirSync (fs.js:808:18)',
     '    at Object.<anonymous> (/usr/local/src/dashkiosk/dashkiosk-2.7.2/dist/lib/express.js:51:18)',
     '    at Module._compile (module.js:409:26)',
     '    at Object.Module._extensions..js (module.js:416:10)',
     '    at Module.load (module.js:343:32)',
     '    at Function.Module._load (module.js:300:12)',
     '    at Module.require (module.js:353:17)',
     '    at require (internal/module.js:12:17)',
     '    at Object.<anonymous> (/usr/local/src/dashkiosk/dashkiosk-2.7.2/dist/server.js:12:11)' ] }
```

I expected a nice list of command line options instead.

**Comment by vincentbernat** [comment]
There is no `--help` option. Options are documented here: http://dashkiosk.readthedocs.io/en/latest/configuration.html. I don't see an easy way to add a `--help` option with the currently used framework.

As for the actuel error, you need to use `--environment production` when running out of `dist` directory.

**Comment by vincentbernat** [comment]
Not much to do here. Closing.

**Comment by JulienPalard** [comment]
oO

**Comment by vincentbernat** [comment]
Did I close the issue too fast?

**Comment by JulienPalard** [comment]
I think, as you did not fixed the issue, but it's your project, you do whatever peases you. I was expressing my surprise.

**Comment by vincentbernat** [comment]
I have added a `--help` flag but it's not very useful as the framework used to ensure configuration doesn't generate the usage string automatically from the accepted arguments:

```
Usage: /usr/bin/nodejs server.js

See http://dashkiosk.readthedocs.io/en/v2.7.2/configuration.html for more
information.
```

**Comment by JulienPalard** [comment]
That's better than giving an exception, thanks a lot! Take care.
