### ISSUE TITLE
Can't install firefox app in firefox 51.0-1

### ISSUE THREAD

**Issue by JulienPalard** [vincentbernat/dashkiosk#55]
I'm using firefox 51.0-1 from Debian sid, and the `/firefox` page tell me:

> This page would install Dashkiosk receiver for Firefox. Please, open it in Firefox browser.

**Comment by vincentbernat** [comment]
This endpoint was for Firefox OS. It is now obsolete and has been removed from Firefox too: http://www.ghacks.net/2016/01/09/mozilla-to-remove-webrt-from-firefox/. The regular receiver should work just fine with Firefox.
