### ISSUE TITLE
Exemple for password protection

### ISSUE THREAD

**Issue by lonvan** [vincentbernat/dashkiosk#57]
Hi Vincent,

First, thank you for this amazing product!

Can you give me an exemple about how to enable password protection for dashkiosk?

Actually I tried to launch Dashkiok on the server with something like:

`node server.js --environment production --auth.enabled --auth.username admin --auth.password password`

but it doesn't work. :-(

I think I miss something.

Thank you.

**Comment by vincentbernat** [comment]
Using exactly your command-line, I am able to get a password prompt when trying to access the server. What do you mean by "doesn't work"?

**Comment by lonvan** [comment]
Thank you for your quick response. ;-)

Dashkiosk works with this command but I'm not prompt for password when I try to reach admin panel (with url like http://dashkiosk:9400/admin) or receiver.

**Comment by vincentbernat** [comment]
❦ 10 février 2017 05:17 -0800, lonvan <notifications@github.com> :

> Dashkiosk works with this command but I'm not prompt for password when
> I try to reach admin panel (with url like http://dashkiosk:9400/admin)
> or receiver.

Right, it seems to only work for protecting "/". I am looking at that...

**Comment by vincentbernat** [comment]
It's fixed with d9f4a16dbd29.
