### ISSUE TITLE
dashboard moving bug

### ISSUE THREAD

**Issue by helmerfud** [vincentbernat/dashkiosk#59]
hello,
i have a bug on drag and drop function.
I have three groups: 
- view1
contain 10 dashboards
- view2
contain 4 dashboards
-repo
contain 50 dashboards for repository and history

when i drag and drop some dashboard from repo group to view1 or view2 the last dashboard is duplicate with a rank of 20002 and that break the schedule of the group.
i have read the log file and it seems like dashkiosk restart.
sometimes i have two dashboard with a rank 20002.

i have to drop all of the group and dashboard to retrieve a fully functional dashkiosk
i use ubuntu 16.04 lts, node v6.10.0, npm 3.10.10, mysql 5.7

sorry for poor english.
i hope this help.

regards.

**Comment by vincentbernat** [comment]
You need to provide me some logs from the server. It should say why Dashkiosk restarts.

**Comment by helmerfud** [comment]
hello,
i have restart dashkiosk with empty log file. 
log file set to debug.
dashkiosk run two schedules and i stop it.

thank you.
best regards.


[dashkiosk.zip](https://github.com/vincentbernat/dashkiosk/files/830224/dashkiosk.zip)

**Comment by vincentbernat** [comment]
I don't see anything special in the logs. Did the bug happened during the run?

**Comment by helmerfud** [comment]
hello,
sorry for the delay.
Yes the schedule restart during this test and before the end of the scenario.
in the log it is about line 74
thank you

**Comment by vincentbernat** [comment]
I didn't understand the bug correctly. The bug is that you manage to get two dashboards with the same rank, right? You can fix this manually in the database if needed. I'll more into it.

**Comment by vincentbernat** [comment]
After a few tries, I am unable to reproduce the problem. New dashboards get a rank of "20002" (this is a way to put them at the end). This is also the case when moving one dashboard from a group to another: its rank changes to "20002". Before inserting a new dashboard or moving one, the destination group ranks are recomputed (3, 7, 5, 9, 11, ...). I don't remember why I have this odd system.

If you are easily able to reproduce the problem, can you run the following command (assuming you use a SQLite database):

```
sqlite3 db/whatever-path-to-db-is
```

Then:

```
select d.rank,d.description,g.name from Dashboards d, Groups g where d.groupId = g.id and g.name=="New group 8PQQN4";
```

Replace the group name by the name of your third group. Run this command before the problem and after the problem.

**Comment by vincentbernat** [comment]
I would need more information. Reopen if you can investigate a bit more.
