### ISSUE TITLE
Change dashboards number per line

### ISSUE THREAD

**Issue by rockyluke** [vincentbernat/dashkiosk#62]
Hello,

Thanks for the great work you've done with Dashkiosk.

Is there a regular way (instead changing style) to display 4 dashboards per line instead of 2. Actually I've a screen wall of 4x3 screen and I want to "reproduce" it in dashkiosk.

Thank.

**Comment by vincentbernat** [comment]
You can try to modify this file: https://github.com/vincentbernat/dashkiosk/blob/master/app/views/groups.html. Replace `col-md-6` by `col-md-3`.

**Comment by rockyluke** [comment]
It work well but now, each dashboard is really small. I can't see complete screen name.

(sorry I'm a cow in css/style).

Thanks.

**Comment by vincentbernat** [comment]
You can also widen the viewport by adding:

```
@container-lg: 1400px;
```

In `app/styles/admin.less` (after the `@import` I think, but if it won't work, try before).

**Comment by rockyluke** [comment]
Work perfectly !

Thanks a lot.
