### ISSUE TITLE
Refresh doesn't work when there's only one dashboard

### ISSUE THREAD

**Issue by rockyluke** [vincentbernat/dashkiosk#63]
Hello,

Actually we've only one dashboard (weathermap) on one screen and the refresh doesn't work.

We've the last master une production.

**Comment by vincentbernat** [comment]
You could just duplicate the dashboard. It's unlikely I find time to fix that in the next weeks.

**Comment by rockyluke** [comment]
I'll take a look, thanks for your answer !
