### ISSUE TITLE
invalid security certificate

### ISSUE THREAD

**Issue by hihouhou** [vincentbernat/dashkiosk#66]
Hello,

I use an self signed certificate and I can't display it with receiver.
I have the message "SEC_ERROR_UNKNOWN_USER"
I have imported the certificate to firefox.
I have put the crt in /usr/share/ca-certificates/extra/ and done dpkg-reconfigure ca-certificates but nothing works.
Could you help me?

Regards,

Hihouhou

**Comment by vincentbernat** [comment]
Maybe just add an exception?

**Comment by hihouhou** [comment]
where?

**Comment by hihouhou** [comment]
up :-)

**Comment by vincentbernat** [comment]
If you get the error, it means the exception is not set. Or the certificate may be invalid. The receiver is just a web app, it doesn't manage certificates. Try with Chrome to see if you get the same error.

**Comment by vincentbernat** [comment]
Not much I can do here.
