### ISSUE TITLE
Chromecast mDNS (not really an issue)

### ISSUE THREAD

**Issue by plitewaikato** [vincentbernat/dashkiosk#68]
Hi all,

I'd like to connect a Chromecast on another non-local VLAN to my Dashkiosk server, but of course the server never sees the local mDNS advertisement from the Chromecast.  Rather than mess around with mDNS reflection or DNS-SD (which I don't think works with Chromecasts anyway) it would save me a bunch of time if someone can dump any info they have for creating a local mDNS "Chromecast" advertisement on _googlecast._tcp._local. that points a non-local IP.  Perhaps by using avahi or the macOS dns-sd binary.

Cheers.

**Comment by vincentbernat** [comment]
This should be possible with `avahi-publish` (twice, once with `-a` to publish the host address and once with `-s -H` to publish the service).

**Comment by plitewaikato** [comment]
Thanks Vincent, I'll give that a try today.  I'm surprised there's no tools
that make this easier, it would be a great solution for Apple TVs in
enterprise too.

**Comment by vincentbernat** [comment]
Not much else to do. Closing this issue.
