### ISSUE TITLE
/firefox redirect to /receiver

### ISSUE THREAD

**Issue by hihouhou** [vincentbernat/dashkiosk#69]
Hello,

When I want adding an other receiver (with firefox) and I use http://<MY_SERVER>/firefox, I'm always redirected to /receiver.
What's happen ? Can I install manually the plugin?

**Comment by vincentbernat** [comment]
If you want to have another receiver in the same browser, the current solution is to use a separate profile.

**Comment by vincentbernat** [comment]
It's expected. `/firefox` was for Firefox OS. Since the OS doesn't exist anymore, it now just redirect to the normal receiver (which should work fine with Firefox the browser).

**Comment by vincentbernat** [comment]
Not a bug. Not much to do.
