### ISSUE TITLE
Chromecast and authentication

### ISSUE THREAD

**Issue by ssozonoff** [vincentbernat/dashkiosk#70]
Are there any links or information on how to handle displaying Dashboard's on Chromecast  which are behind Basic Auth ? Typically we have several performance dashboards we would like to display using DashKiosk and Chromecasts but it proving to be a problem since they are all password protected with Basic Auth.

**Comment by vincentbernat** [comment]
Does encoding the user password inside the URL work? https://user:password@dashboard.example.com.

**Comment by ssozonoff** [comment]
Thats the approach I took but it does not work, possibly an issue related to my Dashboard solution or infra. I just thought that displaying secured sites would have been common enough that someone would have solved it already :-)

**Comment by vincentbernat** [comment]
Maybe the Chromecast doesn't support those kind URL. This would be understandable if there is no UI for them. For Dashkiosk, they are not special.

**Comment by Raboo** [comment]
I don't think this is something that dashkiosk can fix, it's a Chrome thing.

The only solution I found was running a reverse proxy that adds the auth header. And have dashkiosk URLs pointed to the the reverse proxy url instead of the real url.

Example nginx config:
```
server {
  listen 80;
  location / {
    proxy_pass https://real.url/;
    proxy_set_header X-Forwarded-For $remote_addr;
    # basic auth, generate using echo -n "USERNAME:PASSWD" | base64
    proxy_set_header Authorization "Basic VVNFUk5BTUU6UEFTU1dE";
  }
```

**Comment by ssozonoff** [comment]
Thanks for looking... this is pretty much the approach I ended up adopting.
