### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by noxish** [vincentbernat/dashkiosk#76]
Hi, me again :) 

is it possible to use authentication, and pass credentials via url or session id?

like http authentication 
user:pass@domain.com

or is it possible to only force authentication for admin panel?

**Comment by vincentbernat** [comment]
Do you mean for dashboards to be displayed or for dashkiok itself? For dashboards being displayed, you should be able to include them in the URL: https://user:pass@dash.example.com.

**Comment by noxish** [comment]
No i mean the Login into Dashkiosk, but i done it already with a reverse proxy and location /admin
* but i dont want to reopen a new ticket is it possible to disable unassigned tab?
