### ISSUE TITLE
receiver?

### ISSUE THREAD

**Issue by Noname2244** [vincentbernat/dashkiosk#78]
Settings up the server is easy.

but what about the RPIs? It's not clear in the documentation . Is it a addon to the browser?

**Comment by vincentbernat** [comment]
For the Raspberry Pi, use your favorite browser as a receiver (same URL as for the administration panel, without `/admin`).

**Comment by Noname2244** [comment]
Ok, but what do you install on the RPIs?

**Comment by vincentbernat** [comment]
I've switched to Android for this reason. You can try Chromium but it lacks hardware acceleration, so depending on your dashboards, it may be too slow. At some point, Epiphany was worked on to get hardware acceleration. I don't know if that's the case now.

**Comment by Noname2244** [comment]
Im gonna setup grafana on a couple of screens. What do you recommend to install ? If not android.

**Comment by vincentbernat** [comment]
I have not used Raspberry Pi since a few years. Try Chromium.

**Comment by vincentbernat** [comment]
There is not much to do here. Closing.
