### ISSUE TITLE
Auth basic urls

### ISSUE THREAD

**Issue by dchaumond** [vincentbernat/dashkiosk#82]
Hi,

Trying to access basic authenticated urls, I'm not able to make working http://login:pwd@... urls
Reading at some issue here, it seems dashkiosk handle that (https://github.com/vincentbernat/dashkiosk/issues/28) 

My urls works fine on the client side setting manually login information. But adding login/pwd un the urls, my client doesn't seem to be able to load the page (wait). As I want to setup a kiosk client, I need to enter authentication in some automated way.

Tried with latest and 2.6.6 (docker) versions.

Thks, really nice tool.

**Comment by vincentbernat** [comment]
Load dashkiosk receiver from a browser and look into the console (F12). I think your problem is not related to authentication, but to the presence of an `X-Frame-Options` header.

**Comment by vincentbernat** [comment]
Good to know but unfortunately, I don't see an easy workaround. :(

**Comment by dchaumond** [comment]
The only workaround I see is to use a reverse proxy as describe in another issue here.  I've workaround my problem using another way.
