### ISSUE TITLE
Not all chromecast are discovered 

### ISSUE THREAD

**Issue by sarojamarraj** [vincentbernat/dashkiosk#83]
There are a total of 8 chromecast running in the network when I host docker instance and it doesn't discover all of them, only 3 are visible on the admin page

+ ens160 IPv4 Google-Cast-Group-D6ADC5A1A14F40A99B859654AF893998-1 _googlecast._tcp     local
+ ens160 IPv4 Chromecast-bf8c7c85e030a143ae5f2d7c92401e0a   _googlecast._tcp     local
+ ens160 IPv4 Chromecast-e6ccd4c4a1becc7c5b3261921e303380   _googlecast._tcp     local
+ ens160 IPv4 Chromecast-8466d6c32f1d020291dcfdd3c2987430   _googlecast._tcp     local

**Comment by vincentbernat** [comment]
Does `avahi-discover` see them?

**Comment by sarojamarraj** [comment]
avahi-discover gives me below output
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/usr/bin/avahi-discover:64: Warning: invalid (NULL) pointer instance
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: GtkWarning: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: GtkWarning: Screen for GtkWindow not set; you must always set
a screen for a GtkWindow before using the window
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: GtkWarning: IA__gdk_pango_context_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_context_set_font_description: assertion 'context != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_context_set_base_dir: assertion 'context != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_context_set_language: assertion 'context != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_new: assertion 'context != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_set_text: assertion 'layout != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_set_attributes: assertion 'layout != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_set_alignment: assertion 'layout != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_set_ellipsize: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_set_single_paragraph_mode: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_set_width: assertion 'layout != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: PangoWarning: pango_layout_get_extents: assertion 'layout != NULL' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: GtkWarning: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: GtkWarning: IA__gdk_colormap_get_visual: assertion 'GDK_IS_COLORMAP (colormap)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: GtkWarning: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
  self.ui.add_from_file(path)
/usr/bin/avahi-discover:64: GtkWarning: IA__gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed
  self.ui.add_from_file(path)


When run avahi-browse -a ,I get only 3 chromecast

**Comment by vincentbernat** [comment]
Dashkiosk is using Avahi to get the chromecasts. If Avahi is only able to see 3 of them, there is not much it can do.

**Comment by vincentbernat** [comment]
If Avahi can't see them, it's unlikely the problem is in Dashkiosk.
