### ISSUE TITLE
Connection declined from websites

### ISSUE THREAD

**Issue by RobinHorner** [vincentbernat/dashkiosk#86]
So I tried to link a website in dashkiosk but there's always an error that it can't even connect. " 'website' declined the connection" . But if I put the link in the normal browser it works fine.

**Comment by vincentbernat** [comment]
Which receiver are you using?

**Comment by RobinHorner** [comment]
> Which receiver are you using?

localhost:9400/receiver

**Comment by vincentbernat** [comment]
From a browser then? Can you post a screenshot of what you get? Is it an error from the browser? Note, that the remote site has to accept to be enclosed into an iframe. See https://dashkiosk.readthedocs.io/en/latest/usage.html#iframes.

**Comment by RobinHorner** [comment]
![2019-07-09-141342_1824x984_scrot](https://user-images.githubusercontent.com/52482975/60887169-f4873e00-a253-11e9-86c3-d9282f63a80f.png)
yes a browser

**Comment by vincentbernat** [comment]
I think this is likely to be the `X-Frame-Options` issue. You can confirm with `curl -H` on the URL of the website if you have this header.

**Comment by RobinHorner** [comment]
sorry but I don't get it what to do exactly, do I have to type curl -H in the terminal? I'm kinda new to this btw...

**Comment by RobinHorner** [comment]
I was never in touch with IFrame I guess...

**Comment by vincentbernat** [comment]
Yes, in a terminal, `curl -H http://monitor.cedes.com/remaining/of/the/URL`. Check if it returns a line starting with `X-Frame-Options`.

**Comment by RobinHorner** [comment]
I get the output "curl: no URL specified!"

**Comment by vincentbernat** [comment]
Sorry, this is `curl -I`, not `curl -H`.

**Comment by RobinHorner** [comment]
my output now: 
"HTTP/1.1 200 OK
Date: Tue, 09 Jul 2019 13:02:50 GMT
Server: Apache/2.4.29 (Ubuntu)
Set-Cookie: zbx_sessionid=927319758548b551e16ed2d7f5dd838c; HttpOnly
Set-Cookie: PHPSESSID=r5oo1ul6j588cofghcv2k5jrr1; path=/zabbix/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=r5oo1ul6j588cofghcv2k5jrr1; path=/zabbix/; HttpOnly
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=UTF-8"

**Comment by vincentbernat** [comment]
So, the `X-Frame-Options` header is why you can't make it work. Maybe you can teach Apache to remove it.

**Comment by RobinHorner** [comment]
I got no plan how I could do this...

**Comment by RobinHorner** [comment]
anyways thanks a lot for your help

**Comment by RobinHorner** [comment]
> So, the `X-Frame-Options` header is why you can't make it work. Maybe you can teach Apache to remove it.

okay so I basically know a lot more about the problem now, do I have to change the options on the server of the website or on my dashkiosk raspberry?

**Comment by vincentbernat** [comment]
On the server of the website.

**Comment by RobinHorner** [comment]
okay thanks I'm ready to go now :)
