### ISSUE TITLE
Conflicting sqlite3 dependency

### ISSUE THREAD

**Issue by JulienPalard** [vincentbernat/dashkiosk#91]
In the `package.json` there may be an inconsistency:
```
$ grep sqlite package.json
package.json:    "sqlite3": "~4.0.9",
package.json:    "sqlite3": "~3.1.0",
```

So if I lock it using `npm i --package-lock-only` it have to choose. It currently chooses `4.0.9`, which conflicts with `~3.1.0`.

Leading to `npm ci` failing with:

    Invalid: lock file's sqlite3@4.0.9 does not satisfy sqlite3@~3.1.0

**Comment by vincentbernat** [comment]
Thanks, I've pushed a commit fixing this.
