### ISSUE TITLE
Dashkiosk for hundreds or thousands of displays.

### ISSUE THREAD

**Issue by ned-kelly** [vincentbernat/dashkiosk#92]
Hi,

Looking to use Dashkiosk (via the API) for a setup with several hundred displays (in a cloud based system), expanding to around 1200 at a later date (Hardware managed with Balena) - Architecturally - from a technical scale point of view would this be possible with one big server or would I be better having multiple dashkiosk servers (in various docker containers, still on 1-2 big servers in AWS) for each venue? (each venue has about 12 screens).

It's also worth nothing, there would probably only be a handful of groups (say 12-15) - and then each group would be looking at 50-100 screens in it...

This is also a low-budget internal IT solution, so I'd like to avoid purchasing commercial solutions, and have the team further contribute to open source if possible.

**Comment by vincentbernat** [comment]
Hello,

Unfortunately, I can't say for sure. I would say, it should be able to handle thousands of displays without issue, but I may miss some bottlenecks, notably on the database side. You may have to try yourself.

**Comment by ned-kelly** [comment]
> You may have to try yourself.

Not a problem - Looks like AWS EC2 Spot instances for a test, here we go!

I'll post back if there's any issues.

**Comment by ned-kelly** [comment]
Quick update, have it working with about 1,200 displays and counting - running on an AWS m5a.large and all seems ok which is awesome - granted screens only change once a day, and we're controlling dashkiosk via the API not the UI.
