### ISSUE TITLE
cache dashboard pages

### ISSUE THREAD

**Issue by smenzer** [vincentbernat/dashkiosk#93]
I'm using dashkiosk to rotate through about 15 kibana dashboards every 30 seconds. Most of these dashboards have data that only updates about once per hour, but we do want to keep them rotating so we can see them on the TV in the office. Some of these dashboards are fairly processor-heavy with a lot of data, which is causing our kibana/elasticsearch servers to become strained.

It would be great if there was an option in dashkiosk to cache the results of the loaded url and only re-load it every X seconds/minutes. This would let me display each dashboard for 30 seconds, but then refresh the contents once per hour.

Is this something that would be possible for you to add?

Thanks!

**Comment by vincentbernat** [comment]
In the future, we may have the server render the dashboards and push them to the clients. But currently, I don't have a good solution for your use case as the rendering is done by each client.

**Comment by smenzer** [comment]
ok makes sense...thanks!
