### ISSUE TITLE
Chromecasts suddenly stopped working

### ISSUE THREAD

**Issue by maartenberg** [vincentbernat/dashkiosk#94]
Hi,

We've used Dashkiosk for some time now to show a dashboard on four of our Chromecasts. These dashboards are shown on TV screens which we turn off daily (which also turns off the Chromecasts), so we rely on Dashkiosk's Chromecast management to have the Chromecast show Dashkiosk after restarting.

Since last Thursday (2019-09-12), none of our Chromecasts seem to be detected by Dashkiosk anymore. Dashkiosk shows this error in the logs, where it seems to have detected one of our Chromecasts, but can't connect to it:

```
sep 18 10:41:37 dash-nuc node[12252]: 2019-09-18T08:41:37.120Z - info: New Chromecast device discovered
sep 18 10:41:37 dash-nuc node[12252]: { address: '10.0.8.12',
sep 18 10:41:37 dash-nuc node[12252]:   port: 8009,
sep 18 10:41:37 dash-nuc node[12252]:   id: 'c015fc8028f7bef09e0af4c95193fa70',
sep 18 10:41:37 dash-nuc node[12252]:   friendlyName: 'Development 1 TV' }
sep 18 10:41:37 dash-nuc node[12252]: 2019-09-18T08:41:37.368Z - error: An error occurred with some Chromecast device { stack:
sep 18 10:41:37 dash-nuc node[12252]:    [ 'Error: authentication data while already authenticated',
sep 18 10:41:37 dash-nuc node[12252]:      '    at CastChannel.codec.to.auth (/opt/dashkiosk-2.7.7/dist/node_modules/nodecastor/lib/channel.js:347
sep 18 10:41:37 dash-nuc node[12252]:      '    at TLSSocket.readable (/opt/dashkiosk-2.7.7/dist/node_modules/nodecastor/lib/channel.js:118:31)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at emitNone (events.js:106:13)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at TLSSocket.emit (events.js:208:7)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at emitReadable_ (_stream_readable.js:513:10)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at emitReadable (_stream_readable.js:507:7)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at addChunk (_stream_readable.js:274:7)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at readableAddChunk (_stream_readable.js:250:11)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at TLSSocket.Readable.push (_stream_readable.js:208:10)',
sep 18 10:41:37 dash-nuc node[12252]:      '    at TLSWrap.onread (net.js:607:20)' ],
sep 18 10:41:37 dash-nuc node[12252]:   message: 'authentication data while already authenticated' }
...
sep 18 10:41:37 dash-nuc node[12252]:   id: 'c015fc8028f7bef09e0af4c95193fa70',
sep 18 10:41:37 dash-nuc node[12252]:   friendlyName: 'Development 1 TV',
sep 18 10:41:37 dash-nuc node[12252]:   address: '10.0.8.12',
sep 18 10:41:37 dash-nuc node[12252]:   port: 8009,
```

We have also noticed that while the Chromecasts do show up in `avahi-browse _googlecast._tcp`, the IP addresses don't get resolved when using `getent hosts Chromecast-c015fc8028f7bef09e0af4c95193fa70.local`.
We are able to ping the Chromecasts from the host running Dashkiosk, and can also use Google Chrome from that host to cast the dashboard manually to the affected Chromecasts.
The host running Dashkiosk runs Ubuntu 18.04 (Desktop version).

We have tried the following:
- Restarting Dashkiosk
- Factory resetting Chromecasts
- Rebooting the host running Dashkiosk
- Running system updates
- Update Dashkiosk itself (we were on version 2.7.3, and also tested with 2.7.7)

Do you have any idea what might have caused this issue?

**Comment by vincentbernat** [comment]
It seems there is a change in the protocol used by the Chromecasts. You may just try to comment the condition in `/opt/dashkiosk-2.7.7/dist/node_modules/nodecastor/lib/channel.js`, line 347 and check if it helps.

Also, you could check if another client is working correctly. For example [go-chromecast](https://github.com/vishen/go-chromecast) with the `go-chromecast status` command.

**Comment by maartenberg** [comment]
Thank you, this worked! I edited this condition out, restarted Dashkiosk and then the Chromecasts, and this seems to have resolved the problem.

**Comment by vincentbernat** [comment]
Great to hear! I need to investigate a bit to see if there is not a proper fix.
