### ISSUE TITLE
Docker arm container

### ISSUE THREAD

**Issue by bartvanhoutte** [vincentbernat/dashkiosk#97]
Any chance of releasing a Docker image that works on arm (rpi)?

I've tried building the image myself, but I'm getting various errors.

**Comment by vincentbernat** [comment]
I'll do that once we solve #98.

**Comment by tlourey** [comment]
As #98 looks to now have a [solution](https://github.com/vincentbernat/dashkiosk/issues/98#issuecomment-714933888) is there any chance the arm image may go ahead?

**Comment by vincentbernat** [comment]
I have tried to build Docker images for arm64, but the imagemin part fails because it wants to use vendorized optipng or precompiled one from optipng-bin, despite optipng being present on the system. The next step would be to skip this optimisation process which is a bit useless...
